Merge v0.4 with master
molinaris/neuromuscular_notebook pull request #1
Opened 2020-11-11 12:04 UTC by molinaris

2020-11-11 12:41 UTC, molinaris reviewed
v0.4 looking good to merge with master.

2020-11-11 23:00 UTC, leoelias-unicamp requested changes
After reviewing these minor comments you can merge v.0.4 with master.

2020-11-11 23:00 UTC, leoelias-unicamp commented on nerlab/util.py
> +                         description='Plateau/peak intensity [%]:')
Please, change peak intensity to Peak intensity.

2020-11-11 23:00 UTC, leoelias-unicamp commented on neuromuscular_note.ipynb
> +    "The surface electromyogram (sEMG) emerges from the electric activity of the muscle fibres during a given contraction. Currents flowing across the sarcolemma (as a result of the muscle fiber acti
Please, change fibres to fibers.

2020-11-11 23:00 UTC, leoelias-unicamp commented on neuromuscular_note.ipynb
> +    "MU action potentials (MUAP) observed from bipolar electrodes at skin surface can be represented by 1st and 2nd order Hermite-Rodriguez (HR) functions ([Lo Conte et al. 1994](http://doi.org/10.11
Please, change MUAP with MUAPs. Also, rewrite "represented by 1st and 2nd order" as "represented by 1st-order or 2nd-order".

2020-11-11 23:00 UTC, leoelias-unicamp commented on neuromuscular_note.ipynb
> +    "In the present model, the MUAP can represented by either 1st or 2nd order HR functions, which are randomly (equal probability) asigned to the MUs."
Please, rewrite "by either 1st or 2nd order HR" as "by either 1st-order or 2nd-order HR".

2020-11-11 23:00 UTC, leoelias-unicamp commented on neuromuscular_note.ipynb
>      {
I did not see any difference when selecting 1st order or 2nd order in the widget. Is that correct? I am expecting a change in the graph so that in one case we can see biphasic signals while in the other case we can see the triphasic one. Please, check this out. Also, it seems that the font in the 2nd order is larger than in the 1st order radio button.

2020-11-11 23:00 UTC, leoelias-unicamp commented on neuromuscular_note.ipynb
> +    "To mimic experimental recordings, an additive gaussian noise can be summed to the sEMG signal generated by the model. The amplitude of this interference noise is adjusted by the ___Noise standar
At the end of the last phrase, please, include: ", respectively".

2020-11-11 23:00 UTC, leoelias-unicamp commented on neuromuscular_note.ipynb
>     ]
In the widget (In [12]), please, include ":" after each property printed in the lines. For instance,
MU twitch amplitude: 0.39 [mN]
MU twitch time-to-peak: 30.00 [ms]
MU tetanic force: 0.90 [mN]
MU tetanic force at PFR: 0.53 [mN]
MU twitch/tetanus ratio: 43.37 %
MU twitch/tetanus ratio at PFR: 73.11 %
MU force saturation frequency: 100.00 [Hz]
Force saturation frequency of the MU pool (mean +/- std): 64.41 +/- 13.03 [Hz]

2020-11-11 23:00 UTC, leoelias-unicamp commented on neuromuscular_note.ipynb
> +    "- $m_j$ is the $j$-th MU spike time;\n",
Please, change "MU spike time" to "MU spike sample".

2020-11-12 11:37 UTC, molinaris commented on neuromuscular_note.ipynb
>      {
Fixed

2020-11-12 12:24 UTC, merged

2020-11-12 20:11 UTC, leoelias-unicamp commented
Looks great!